# Generated by Django 4.1.3 on 2022-11-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_project_id_alter_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("1", "Stuck"), ("2", "Working"), ("3", "Done")],
                default=1,
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due",
            field=models.CharField(
                choices=[("1", "On Due"), ("2", "Overdue"), ("3", "Done")],
                default=1,
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("1", "Stuck"), ("2", "Working"), ("3", "Done")],
                default=1,
                max_length=7,
            ),
        ),
    ]
#