# Generated by Django 4.1.3 on 2022-11-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_project_id_alter_task_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="efforts",),
    ]
