# Generated by Django 4.1.3 on 2022-11-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0013_alter_company_id_alter_invite_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="company", name="social_name",),
        migrations.RemoveField(model_name="userprofile", name="friends",),
        migrations.DeleteModel(name="Invite",),
    ]
